### ISSUE TITLE
Upgrade FuelPHP Framework to v1.7.2

### ISSUE THREAD

**Issue by dsposito** [volcano/volcano#35]
Version 1.7.2 includes recommended security patches and some new goodies backported from v2.0 (still in beta). 1.7.2 also finally includes full support for Composer packages - both for external packages and internal core components.

http://fuelphp.com/blogs/2014/07/fuelphp-releases-v1-7-2
https://github.com/fuel/core/wiki/Changelog-v1.7.2
-  [ ] Upgrade framework to v1.7.2
-  [ ] Convert submodules to composer packages

**Comment by dmyers** [comment]
Should we move to Laravel?

**Comment by kesali** [comment]
why in earth someone has to more another framework while everything works perfectly?

**Comment by dmyers** [comment]
"Perfectly"...

Something you have to constantly consider in tech is evolution of features with regards to productivity. One big one that comes to mind is composer support. People who were great at Coldfusion thought the same thing.
